export { actualizarInventarioFn } from "./admin-api/inventario";
export { crearAfiliadoFn, buscarPersonaCubiertaFn } from "./admin-api/afiliados";
export { actualizarEstadosBovedasFn } from "./scheduled/actualizar-estados-bovedas";
export { registrarBovedaFn, listarBovedasPorEstadoFn } from "./admin-api/bovedas";
export { asignarRolFn } from "./admin-api/usuarios";
export { registrarServicioFn } from "./admin-api/servicios";
export { crearConvenioFn, guardarTarifaFn } from "./admin-api/convenios";
export { crearTipoCofreFn } from "./admin-api/cofres";
export { crearPlanFn } from "./admin-api/planes";
export { crearFlorFn } from "./admin-api/flores";
export { generarReporteFn } from "./admin-api/reportes";